# Generated by Django 2.2.4 on 2019-08-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=3)),
                ('cost', models.CharField(max_length=5)),
                ('totaltickets', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('city', models.CharField(max_length=10)),
                ('passport', models.CharField(max_length=30)),
                ('vehicle_no', models.CharField(max_length=8)),
                ('reg_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
