# Generated by Django 2.2.4 on 2019-09-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20190828_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='passport',
            new_name='idproof',
        ),
        migrations.AddField(
            model_name='booking',
            name='idno',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
