# Generated by Django 2.2.4 on 2019-09-03 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20190903_0610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='totaltickets',
        ),
    ]
