# Generated by Django 2.2.4 on 2019-09-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_remove_booking_totaltickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
