# Generated by Django 2.2.4 on 2019-09-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20190904_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('ol', 'online'), ('off', 'offline')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_no',
            field=models.CharField(max_length=6),
        ),
    ]
